name: Build and Test

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./backend/ServiceDesk.sln

      - name: Build
        run: dotnet build ./backend/ServiceDesk.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./backend/ServiceDesk.Tests/ServiceDesk.Tests.csproj --no-restore --configuration Debug